version: '3.8'

services:
  cockroach1:
    image: cockroachdb/cockroach:v22.2.19
    container_name: cockroach1
    hostname: cockroach1
    networks:
      - cockroach-net
    ports:
      - "26257:26257"  # SQL Port
      - "8080:8080"    # Admin UI Port
    volumes:
      - cockroach1-data:/cockroach/cockroach-data
    command: start --insecure --advertise-addr=cockroach1:26357 --http-addr=cockroach1:8080 --sql-addr=cockroach1:26257 --listen-addr=cockroach1:26357 --join=cockroach1:26357,cockroach2:26357,cockroach3:26357

  cockroach2:
    image: cockroachdb/cockroach:v22.2.19
    container_name: cockroach2
    hostname: cockroach2
    networks:
      - cockroach-net
    ports:
      - "26258:26257"  # SQL Port (Different from first instance)
      - "8081:8080"    # Admin UI Port (Different from first instance)
    volumes:
      - cockroach2-data:/cockroach/cockroach-data
    command: start --insecure --listen-addr=cockroach2 --advertise-addr=cockroach2:26357 --http-addr=cockroach2:8080 --sql-addr=cockroach2:26257 --listen-addr=cockroach2:26357 --join=cockroach1:26357,cockroach2:26357,cockroach3:26357

  cockroach3:
    image: cockroachdb/cockroach:v22.2.19
    container_name: cockroach3
    hostname: cockroach3
    networks:
      - cockroach-net
    ports:
      - "26259:26257"  # SQL Port (Different from first instance)
      - "8082:8080"    # Admin UI Port (Different from first instance)
    volumes:
      - cockroach3-data:/cockroach/cockroach-data
    command: start --insecure --listen-addr=cockroach3 --advertise-addr=cockroach3:26357 --http-addr=cockroach3:8080 --sql-addr=cockroach3:26257 --listen-addr=cockroach3:26357 --join=cockroach1:26357,cockroach2:26357,cockroach3:26357


networks:
  cockroach-net:

volumes:
  cockroach1-data:
  cockroach2-data:
  cockroach3-data:
